export const routes = {
  login: "/admin/authen/login",
  forgotPassword: "/admin/authen/forgot-password",
  otpPassword: "/admin/authen/otp-password",
  resetPassword: "/admin/authen/reset-password",
  blogList: "/admin/blog",
  blogCreate: "/admin/blog/create",
  blogUpdate: "/admin/blog/update/:id",
  categoryList: "/admin/category",
  categoryCreate: "/admin/category/create",
  categoryUpdate: "/admin/category/update/:id",
  productList: "/admin/product",
  productCreate:"/admin/product/create",
  productUpdate: "/admin/product/update/:id",
  collectionList: "/admin/collection",
  collectionCreate: "/admin/collection/create",
  collectionUpdate: "/admin/collection/update/:id",
  designList: "/admin/design",
  clientList: "/admin/client",
  orderList: "/admin/order",
  wishlistList: "/admin/wishlist",
  dashboard: "/admin/dashboard"
};
