export const routes = {
  login: "/admin/authen/login",
  forgotPassword: "/admin/authen/forgot-password",
  otpPassword: "/admin/authen/otp-password",
  resetPassword: "/admin/authen/reset-password",
  blogList: "/admin/blog",
  blogCreate: "/admin/blog/create",
  blogUpdate: "/admin/blog/update/:id",
  categoryList: "/admin/category",
  categoryCreate: "/admin/category/create",
  categoryUpdate: "/admin/category/update/:id",
  productList: "/admin/product",
  productCreate:"/admin/product/create",
  productUpdate: "/admin/product/update/:id",
  collectionList: "/admin/collection",
  collectionCreate: "/admin/collection/create",
  collectionUpdate: "/admin/collection/update/:id",
  designList: "/admin/design",
  clientList: "/admin/client",
  orderList: "/admin/order",
  wishlistList: "/admin/wishlist",
  roleList: "/admin/role",
  roleCreate: "/admin/role/create",
  roleUpdate: "/admin/role/update/:id",
  settingList: "/admin/setting",
  settingAccountList: "/admin/setting/account",
  settingAccountCreate: "/admin/setting/account/create",
  settingAccountUpdate: "/admin/setting/account/update/:id",
  settingWebsiteInfo: "/admin/setting/website-info",
  dashboard: "/admin/dashboard",
  sizeList: "/admin/sizes",
  colorList: "/admin/colors",
  materialList: "/admin/materials"
};
